FROM python:3.10

WORKDIR /proj

COPY ./requirements.txt /requirements.txt

RUN apt-get update \
    && apt-get install gcc -y \
    && apt-get clean

RUN pip install -r /requirements.txt \
    && rm -rf /root/.cache/pip

COPY . /proj/app

CMD [ "python3", "-m", "app.main" ]